# Generated by Django 4.2.3 on 2023-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.CharField(max_length=200)),
                ('glucose', models.CharField(max_length=200)),
                ('bloodpressure', models.CharField(max_length=200)),
                ('skinthickness', models.CharField(max_length=200)),
                ('insulin', models.CharField(max_length=200)),
                ('bmi', models.CharField(max_length=200)),
                ('diabetespedigreefunction', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
    ]
